[package]
name = "dear-imnodes"
version = "0.1.0"
edition.workspace = true
description = "Safe, idiomatic Rust bindings for ImNodes (node editor for Dear ImGui)"
license.workspace = true
repository.workspace = true
homepage.workspace = true
categories.workspace = true
keywords.workspace = true

[dependencies]
dear-imgui = { path = "../../dear-imgui", version = "0.2" }
dear-imnodes-sys = { path = "../dear-imnodes-sys", version = "0.1" }
bitflags.workspace = true
thiserror.workspace = true

[features]
default = []
# Docking is always enabled; remove feature.
# Enable multi-viewport support (commented out while WIP)
# multi-viewport = ["dear-imgui/multi-viewport", "dear-imnodes-sys/multi-viewport"]
freetype = ["dear-imgui/freetype", "dear-imnodes-sys/freetype"]
