[changelog]
header = """
# Changelog

All notable changes to this project are documented here.

"""
body = """
{% for release in releases %}
## {{ release.version | default(value="Unreleased") }}{% if release.timestamp %} ({{ release.timestamp | date(format="%Y-%m-%d") }}){% endif %}

{% if release.commits | length == 0 %}
- No significant changes.
{% endif %}

{% for group, commits in release.commits | group_by(attribute="group") %}
### {{ group | upper_first }}
{% for commit in commits %}
- {{ commit.message | trim }}{% if commit.breaking %} (BREAKING){% endif %}{% if commit.scope %} [{{ commit.scope }}]{% endif %} ({{ commit.id | truncate(length=7) }}){% if commit.author.name %} by @{{ commit.author.name }}{% endif %}
{% endfor %}
{% endfor %}

{% endfor %}
"""
trim = true

[git]
conventional_commits = true
filter_unconventional = true
split_commits = false
tag_pattern = ".*"
protect_breaking_commits = true
skip_tags = false

# Group commits by conventional prefixes
commit_parsers = [
  { message = "BREAKING CHANGE", group = "Breaking Changes" },
  { message = "^feat", group = "Features" },
  { message = "^fix", group = "Fixes" },
  { message = "^perf", group = "Performance" },
  { message = "^refactor", group = "Refactor" },
  { message = "^docs", group = "Docs" },
  { message = "^build|^deps|^ci", group = "Build" },
  { message = "^chore|^style|^test", group = "Chore" }
]

