[package]
name = "build-support"
version = "0.1.0"
edition.workspace = true
publish = false

[lib]
name = "build_support"
path = "src/lib.rs"

[dependencies]
reqwest = { version = "0.12", features = ["blocking", "rustls-tls"], default-features = false }
flate2 = "1"
tar = "0.4"

