[package]
name = "dear-imgui-build-support"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
categories.workspace = true
keywords.workspace = true
description = "Build helpers for dear-imgui-sys family: compose archive names, prebuilt download/extract, manifest helpers"

[lib]
name = "build_support"
path = "src/lib.rs"

[dependencies]
reqwest = { version = "0.12", features = ["blocking", "http2", "rustls-tls"], default-features = false }
flate2.workspace = true
tar.workspace = true

