[package]
name = "dear-implot-sys"
version = "0.2.0"
edition.workspace = true
description = "Low-level FFI bindings for ImPlot via cimplot (C API)"
license.workspace = true
repository.workspace = true
homepage.workspace = true
categories.workspace = true
keywords.workspace = true
build = "build.rs"
links = "dear_implot"

# docs.rs configuration for offline builds
[package.metadata.docs.rs]
no-default-features = true
all-features = false
features = []
rustdoc-args = ["--cfg", "docsrs"]

# Exclude heavy upstream folders from package tarball
exclude = [
    "third-party/cimplot/example_glfw_opengl3/**",
    "third-party/cimplot/generator/**",
    "third-party/cimplot/implot/.github/**",
    "third-party/cimplot/implot/examples/**",
    "third-party/cimplot/implot/misc/**",
    "third-party/cimplot/implot/docs/**",
]

[dependencies]
dear-imgui-sys = { path = "../../dear-imgui-sys", version = "0.2" }
#mint.workspace = true
#cfg-if.workspace = true
flate2 = { version = "1", optional = true }
tar = { version = "0.4", optional = true }

[build-dependencies]
bindgen.workspace = true
cc.workspace = true
xshell = "0.2"
pkg-config = "0.3"
reqwest = { version = "0.11", features = ["blocking", "rustls-tls"], default-features = false }
flate2 = "1"
tar = "0.4"
cmake = "0.1"

[[bin]]
name = "package"
path = "bin/package/main.rs"
required-features = ["package-bin"]

[features]
package-bin = ["dep:flate2", "dep:tar"]
default = ["prebuilt"]
# Docking is always enabled; feature removed.
# Enable multi-viewport support (commented out while WIP)
# multi-viewport = ["dear-imgui-sys/multi-viewport"]
# Enable freetype font rasterizer
freetype = ["dear-imgui-sys/freetype"]
# Enable for WASM targets
# wasm = ["dear-imgui-sys/wasm"]
prebuilt = []
build-from-source = []
