[package]
name = "dear-imgui-winit"
version = "0.2.0"
edition.workspace = true
description = "Winit backend for Dear ImGui"
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation = "https://docs.rs/dear-imgui-winit"
categories.workspace = true
keywords.workspace = true

[dependencies]
dear-imgui = { path = "../../dear-imgui", version = "0.2" }
winit.workspace = true
#raw-window-handle = "0.6"
#cfg-if.workspace = true
instant = { version = "0.1", features = ["wasm-bindgen"] }

# WASM-specific dependencies
[target.'cfg(target_arch = "wasm32")'.dependencies]
web-sys = { version = "0.3", features = [
    "Document",
    "Element",
    "HtmlCanvasElement",
    "Window",
] }

[features]
default = []
# Enable multi-viewport support (WIP). Declared to silence cfg warnings; kept off by default.
multi-viewport = []
