name: Bug report
description: File a bug to help us reproduce and fix issues quickly.
labels: [bug, triage]
body:
  - type: checkboxes
    id: crates
    attributes:
      label: Affected crates
      description: Select all crates impacted by this issue.
      options:
        - label: dear-imgui
        - label: dear-imgui-sys
        - label: backends/dear-imgui-wgpu
        - label: backends/dear-imgui-glow
        - label: backends/dear-imgui-winit
        - label: extensions/dear-implot
        - label: extensions/dear-implot-sys
        - label: extensions/dear-imnodes
        - label: extensions/dear-imnodes-sys
        - label: extensions/dear-imguizmo
        - label: extensions/dear-imguizmo-sys
  - type: checkboxes
    id: targets
    attributes:
      label: Target(s)
      description: Select all that apply.
      options:
        - label: Windows x86_64-pc-windows-msvc (MD)
        - label: Windows x86_64-pc-windows-msvc (MT)
        - label: Linux x86_64-unknown-linux-gnu
        - label: macOS x86_64-apple-darwin
        - label: macOS aarch64-apple-darwin
        - label: wasm32 (unknown or emscripten)
  - type: dropdown
    id: build_strategy
    attributes:
      label: Build strategy used
      options:
        - Source build
        - Prebuilt (Release asset)
        - Prebuilt (local package dir)
        - Prebuilt (direct URL)
        - Mixed / Unsure
  - type: checkboxes
    id: features
    attributes:
      label: Relevant features/flags
      options:
        - label: freetype
        - label: build-from-source
        - label: prebuilt (feature)
  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
      description: Smallest possible steps or a minimal repo to reproduce.
      placeholder: |
        1. cargo build -p <crate> [options]
        2. ...
        3. Observe error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior / error logs
      render: shell
    validations:
      required: true
  - type: input
    id: versions
    attributes:
      label: Version info
      description: dear-imgui version(s), commit SHA, rustc/cargo versions.
      placeholder: dear-imgui-sys 0.2.x, rustc 1.xx.x, cargo 1.xx.x
  - type: input
    id: os
    attributes:
      label: OS / Toolchain
      placeholder: Windows 11 23H2, MSVC; Ubuntu 22.04; macOS 14
  - type: textarea
    id: extra
    attributes:
      label: Additional context
