[package]
name = "dear-imgui-examples"
version = "0.1.0"
edition = "2021"

[features]
multi-viewport = ["dear-imgui/multi-viewport", "dear-imgui-winit/multi-viewport"]

[[bin]]
name = "hello_world"
path = "hello_world.rs"

[[bin]]
name = "hello_world_wgpu"
path = "hello_world_wgpu.rs"

[[bin]]
name = "draw_demo"
path = "draw_demo.rs"

[[bin]]
name = "widgets_demo"
path = "widgets_demo.rs"

[[bin]]
name = "game_engine_docking"
path = "game_engine_docking.rs"

[[bin]]
name = "text_filter_demo"
path = "text_filter_demo.rs"

[[bin]]
name = "input_text_callback_demo"
path = "input_text_callback_demo.rs"

[[bin]]
name = "multi_viewport_demo"
path = "multi_viewport_demo.rs"

[[bin]]
name = "test_multi_viewport"
path = "test_multi_viewport.rs"

[[bin]]
name = "test_viewport_callbacks"
path = "test_viewport_callbacks.rs"



[dependencies]
dear-imgui = { path = "../dear-imgui" }
dear-imgui-winit = { path = "../backends/dear-imgui-winit" }
dear-imgui-wgpu = { path = "../backends/dear-imgui-wgpu" }
wgpu = "26.0"
winit = "0.30.12"
env_logger = "0.11"
pollster = "0.4"
