[package]
name = "dear-imgui-examples"
version = "0.1.0"
edition.workspace = true

[features]
multi-viewport = [
    "dear-imgui/multi-viewport",
    "dear-imgui-winit/multi-viewport",
]

[[bin]]
name = "wgpu_basic"
path = "wgpu_basic.rs"

[[bin]]
name = "game_engine_docking"
path = "game_engine_docking.rs"

[[bin]]
name = "test_msvc_abi_issue"
path = "test_msvc_abi_issue.rs"

[[bin]]
name = "glow_basic"
path = "glow_basic.rs"

[[bin]]
name = "glow_textures"
path = "glow_textures.rs"

[[bin]]
name = "implot_basic"
path = "implot_basic.rs"

[[bin]]
name = "imguizmo_basic"
path = "imguizmo_basic.rs"

[[bin]]
name = "imnodeflow_basic"
path = "imnodeflow_basic.rs"

[dependencies]
dear-imgui = { path = "../dear-imgui" }
dear-imgui-winit = { path = "../backends/dear-imgui-winit" }
dear-imgui-wgpu = { path = "../backends/dear-imgui-wgpu" }
dear-imgui-glow = { path = "../backends/dear-imgui-glow" }
dear-implot = { path = "../extensions/dear-implot" }
dear-imguizmo = { path = "../extensions/dear-imguizmo" }
wgpu = "26.0"
winit = "0.30.12"
tracing.workspace = true
tracing-subscriber.workspace = true
env_logger = "0.11"
pollster = "0.4"
glow = "0.16"
glutin = "0.32"
glutin-winit = "0.5"
raw-window-handle = "0.6"
image = "0.25"
