[package]
name = "dear-imgui-examples"
version = "0.1.0"
edition.workspace = true

[features]
multi-viewport = ["dear-imgui/multi-viewport", "dear-imgui-winit/multi-viewport"]

[[bin]]
name = "hello_world"
path = "hello_world.rs"

[[bin]]
name = "draw_demo"
path = "draw_demo.rs"

[[bin]]
name = "widgets_demo"
path = "widgets_demo.rs"

[[bin]]
name = "game_engine_docking"
path = "game_engine_docking.rs"

[[bin]]
name = "multi_viewport_demo"
path = "multi_viewport_demo.rs"

[dependencies]
dear-imgui = { path = "../dear-imgui" }
dear-imgui-winit = { path = "../backends/dear-imgui-winit" }
dear-imgui-wgpu = { path = "../backends/dear-imgui-wgpu" }
wgpu = "26.0"
winit = "0.30.12"
env_logger = "0.11"
pollster = "0.4"
