[package]
name = "dear-imgui-examples"
version = "0.1.0"
edition.workspace = true

[features]
dear-implot = ["dep:dear-implot"]
dear-imguizmo = ["dep:dear-imguizmo"]
dear-imnodes = ["dep:dear-imnodes"]

[[bin]]
name = "wgpu_basic"
path = "wgpu_basic.rs"

[[bin]]
name = "hello_world"
path = "hello_world.rs"

[[bin]]
name = "game_engine_docking"
path = "game_engine_docking.rs"


[[bin]]
name = "glow_basic"
path = "glow_basic.rs"

[[bin]]
name = "glow_textures"
path = "glow_textures.rs"

[[bin]]
name = "dockspace_minimal"
path = "dockspace_minimal.rs"

[[bin]]
name = "wgpu_textures"
path = "wgpu_textures.rs"

[[bin]]
name = "implot_basic"
path = "implot_basic.rs"
required-features = ["dear-implot"]

[[bin]]
name = "imguizmo_basic"
path = "imguizmo_basic.rs"
required-features = ["dear-imguizmo"]

[[bin]]
name = "imnodes_basic"
path = "imnodes_basic.rs"
required-features = ["dear-imnodes"]


[dependencies]
dear-imgui = { path = "../dear-imgui" }
dear-imgui-winit = { path = "../backends/dear-imgui-winit" }
dear-imgui-wgpu = { path = "../backends/dear-imgui-wgpu" }
dear-imgui-glow = { path = "../backends/dear-imgui-glow" }
dear-implot = { path = "../extensions/dear-implot", optional = true }
dear-imguizmo = { path = "../extensions/dear-imguizmo", optional = true }
dear-imnodes = { path = "../extensions/dear-imnodes", optional = true }
wgpu = "26.0"
winit = "0.30.12"
glam = "0.30"
tracing.workspace = true
tracing-subscriber.workspace = true
env_logger = "0.11"
pollster = "0.4"
glow = "0.16"
glutin = "0.32"
glutin-winit = "0.5"
raw-window-handle = "0.6"
image = "0.25"
