[package]
name = "dear-imguizmo"
version = "0.1.0"
edition.workspace = true
description = "High-level Rust bindings for ImGuizmo (C API) with Dear ImGui integration"
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation = "https://docs.rs/dear-imguizmo"
categories.workspace = true
keywords.workspace = true
readme = "README.md"

[dependencies]
dear-imgui = { path = "../../dear-imgui", version = "0.2" }
dear-imgui-sys = { path = "../../dear-imgui-sys", version = "0.2" }
dear-imguizmo-sys = { path = "../dear-imguizmo-sys", version = "0.1" }
thiserror.workspace = true
bitflags = "2.5"
glam = { version = "0.27", optional = true }
mint = { version = "0.5", optional = true }

[features]
default = ["glam"]
# Docking is always enabled; remove feature.
# Enable multi-viewport support (commented out while WIP)
# multi-viewport = ["dear-imgui/multi-viewport", "dear-imguizmo-sys/multi-viewport"]
freetype = ["dear-imgui/freetype", "dear-imguizmo-sys/freetype"]
glam = ["dep:glam"]
mint = ["dep:mint"]
