[package]
name = "dear-imguizmo"
version.workspace = true
edition.workspace = true
description = "Pure Rust implementation of ImGuizmo - 3D gizmo manipulation library for Dear ImGui"
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation = "https://docs.rs/dear-imguizmo"
categories.workspace = true
keywords.workspace = true
readme = "README.md"

[package.metadata.docs.rs]
features = ["freetype", "docking"]

[dependencies]
bitflags.workspace = true
dear-imgui = { path = "../../dear-imgui", version = "0.1" }
glam = { version = "0.30", features = ["mint"] }
mint.workspace = true
thiserror.workspace = true
tracing = { version = "0.1", optional = true }

[features]
default = ["docking"]
# Enable docking branch features (default)
docking = ["dear-imgui/docking"]
# Enable multi-viewport support (requires docking)
multi-viewport = ["docking", "dear-imgui/multi-viewport"]
# Enable freetype font rasterizer
freetype = ["dear-imgui/freetype"]
# Enable for WASM targets
# wasm = ["dear-imgui/wasm"]
# Enable tracing support for logging
tracing = ["dep:tracing"]

[dev-dependencies]
approx = "0.5"
pretty_assertions = "1.4"
tracing-subscriber = "0.3"
