[package]
name = "dear-imguizmo"
version.workspace = true
edition.workspace = true
description = "High-level Rust bindings for ImGuizmo (C API) with Dear ImGui integration"
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation = "https://docs.rs/dear-imguizmo"
categories.workspace = true
keywords.workspace = true
readme = "README.md"

[dependencies]
dear-imgui = { path = "../../dear-imgui", version = "0.1" }
dear-imguizmo-sys = { path = "../dear-imguizmo-sys", version = "0.1" }
dear-imgui-sys = { path = "../../dear-imgui-sys", version = "0.1" }
thiserror.workspace = true
bitflags = "2.5"
glam = "0.27"

[features]
default = ["docking"]
docking = ["dear-imgui/docking", "dear-imguizmo-sys/docking"]
multi-viewport = ["docking", "dear-imgui/multi-viewport", "dear-imguizmo-sys/multi-viewport"]
freetype = ["dear-imgui/freetype", "dear-imguizmo-sys/freetype"]
