[package]
name = "dear-imguizmo-sys"
version.workspace = true
edition.workspace = true
description = "Low-level FFI bindings for ImGuizmo via cimguizmo (C API)"
license.workspace = true
repository.workspace = true
homepage.workspace = true
categories.workspace = true
keywords.workspace = true
build = "build.rs"
links = "dear_imguizmo"

[dependencies]
dear-imgui-sys = { path = "../../dear-imgui-sys", version = "0.1" }
mint.workspace = true
cfg-if.workspace = true

[build-dependencies]
bindgen.workspace = true
cc.workspace = true
xshell = "0.2"
pkg-config = "0.3"
reqwest = { version = "0.12", features = ["blocking", "rustls-tls"], default-features = false }

[features]
default = ["docking"]
docking = ["dear-imgui-sys/docking"]
multi-viewport = ["docking", "dear-imgui-sys/multi-viewport"]
freetype = ["dear-imgui-sys/freetype"]
