[package]
name = "dear-imguizmo-sys"
version = "0.1.0"
edition.workspace = true
description = "Low-level FFI bindings for ImGuizmo via cimguizmo (C API)"
license.workspace = true
repository.workspace = true
homepage.workspace = true
categories.workspace = true
keywords.workspace = true
build = "build.rs"
links = "dear_imguizmo"

# Exclude heavy upstream folders from package tarball
exclude = [
    "third-party/cimguizmo/ImGuizmo/example/**",
    "third-party/cimguizmo/ImGuizmo/.github/**",
    "third-party/cimguizmo/ImGuizmo/docs/**",
    "third-party/cimguizmo/ImGuizmo/generator/**",
]

[dependencies]
dear-imgui-sys = { path = "../../dear-imgui-sys", version = "0.2" }
mint.workspace = true
cfg-if.workspace = true
flate2 = { version = "1", optional = true }
tar = { version = "0.4", optional = true }

[build-dependencies]
bindgen.workspace = true
cc.workspace = true
xshell = "0.2"
pkg-config = "0.3"
reqwest = { version = "0.12", features = ["blocking", "rustls-tls"], default-features = false }
flate2 = "1"
tar = "0.4"

[[bin]]
name = "package"
path = "bin/package/main.rs"
required-features = ["package-bin"]

[features]
package-bin = ["dep:flate2", "dep:tar"]
default = ["docking"]
docking = ["dear-imgui-sys/docking"]
multi-viewport = ["docking", "dear-imgui-sys/multi-viewport"]
freetype = ["dear-imgui-sys/freetype"]
